language: cpp

os: linux
dist: trusty
sudo: required

before_install:
  - tools/check_signed_off.sh --travis
  - tools/apt-get-install-arm.sh
  - tools/apt-get-install-deps.sh
  - deps/jerry/tools/apt-get-install-deps.sh

install:

script: "tools/build.py $OPTS"

env:
  - OPTS="--buildtype=debug"
  - OPTS="--buildtype=release"
  - OPTS="--jerry-lto"
  - OPTS="--no-snapshot"
  - OPTS="--target-arch=arm --target-board=rpi2"
  - OPTS="--no-check-test --iotjs-exclude-module assert --iotjs-exclude-module dns --iotjs-exclude-module gpio --iotjs-exclude-module i2c --iotjs-exclude-module http --iotjs-exclude-module net --iotjs-exclude-module pwm --iotjs-exclude-module stream"
