language: c

os: linux
dist: trusty
sudo: required

services:
  - docker

before_install:
  - if [[ "$RUN_DOCKER" == "yes" ]]; then docker pull iotjs/ubuntu:0.6; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tools/brew-install-deps.sh; fi
  - if [[ "$OPTS" == "misc" ]]; then tools/apt-get-install-deps.sh; fi

install:
  pip install --user jsonmerge

script:
  tools/travis_script.py

env:
  global:
    - secure: "lUGzoKK/Yn4/OmpqLQALrIgfY9mQWE51deUawPrCO87UQ2GknfQ4BvwY3UT5QY0XnztPBP1+vRQ2qxbiAU7VWicp280sXDnh0FeuZD14FcE9l0FczraL12reoLu+gY5HWFfbkZncmcBsZkxDEYxhkM14FJU8fxyqGQW2ypJNz+gUGP+8r40Re5J3WjcddCQNe5IG8U+M9B4YeDHhN2QspLdN5pkgn56XtdGa3+qbecO2NpjJG5ltM9j1tTuo/Dg22DxrIFVfeFSFKUj4nfMrgPo5LevRsC/lfaBSCsj751eqrxRcQRh2hkpiIJ7mEBs2LL1EH9O6Mbj+eRh8BvIYqTB85VPNFc43sLWk14apcSVBrxJE5j3kP9sAsOD9Y5JynnkeuxYyISrkywwoX2uxsmCzIfGbwsv5VLToQzrqWlGYrHOAmVXNi8561dLfsWwxxFUjdqkZr1Kgc8UfnBEcBUtSiKCHS86/YUUbBJGkEkjDUS0GiqhFY4bXLQCR7EX4qDX3m6p7Mnh4NVUolpnSmyeYE/MjmqQ+7PJsPLL3EcIYmJ7dtW3mZ3yE2NyaFD0Pym9+TiuCCXRtrNVK1M3Kya64KNv+HbhjT/fTCgXLSeyDmJOKVAqugRlDo3b1KGR1LI0AfegzSA6mEC4e9JLjYiSnHPMUahzgLt8oU0hNFRY="
  matrix:
    - OPTS="host-linux" RUN_DOCKER=yes
    - OPTS="rpi2" RUN_DOCKER=yes
    - OPTS="stm32f4dis" RUN_DOCKER=yes
    - OPTS="artik053" RUN_DOCKER=yes
    - OPTS="tizen" RUN_DOCKER=yes
    - OPTS="es2015" RUN_DOCKER=yes
    - OPTS="external-modules" RUN_DOCKER=yes
    - OPTS="no-snapshot" RUN_DOCKER=yes
    - OPTS="misc" RUN_DOCKER=yes

matrix:
  include:
    - os: osx
      env: OPTS="host-darwin"
      install: pip2 install --user jsonmerge
    - compiler: gcc-4.9
      before_install: tools/apt-get-install-travis-i686.sh
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - gcc-4.9-multilib
      env: OPTS="asan" ASAN_OPTIONS=detect_stack_use_after_return=1:check_initialization_order=true:strict_init_order=true
    - compiler: gcc-4.9
      before_install: tools/apt-get-install-travis-i686.sh
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - gcc-4.9-multilib
      env: OPTS="ubsan" UBSAN_OPTIONS=print_stacktrace=1
    - os: linux
      before_install:
        - tools/apt-get-install-deps.sh
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        coverity_scan:
          project:
            name: "Samsung/iotjs"
            description: "Platform for Internet of Things with JavaScript"
          notification_email: duddlf.choi@samsung.com
          build_command: "tools/travis_script.py"
          branch_pattern: master
      env: OPTS="coverity"
    - os: linux
      addons:
        sonarcloud:
          organization: "samsung-iotjs"
          token:
            secure: "NmBlRv6YK9+SiuJRp9E4tQRq8zVGF1MojYnikyIOPGZvWT4jd6eKr86dAwKN6BTevX4nXJ3doGFeF/QVHbXqWDecawpT30OEabpQE7ryYlLyDoNWJ0MfVFzAvBgkpZ0+G52yROgo9yr01r4vDJRoG7QSvDZHh6eGXSTygbJQKej1vmjsRs5bwa2Nyvt+oDhm78V1TroBHGSFMT7ZBWTnzC+YYMdazappJCCYi1ikFLk1aZ6c0tvUaeHl/7a0Tifh0Xt8wQmIaSr60hqZ1Hrq+Z5zJoOoXJ75VzNoHNksuffS4HS84h1KU2I/Z0P9PngHra9y04s4e0RS+tRX+RWkwjhsN8VJgVD8/EMUvaxG5WkQ/Czweiqfe78sTM1jpmdupaGP/IVmsqujodzTho8sY6hyzXcoHXj1fPZPx75HCwaOA7MqMZA1pyKh6U6W4gNVSeDw/+Y6z18fB+VZBXnrljmfWYY2QD/faLccF89ICYOVz/vAFn3b6D6sJwekeM0Nj6h0XO+Ny/81Y6H47u9otXmuDd0pZoGgypBjeSbiRJsGLJNnxZQziBnIl7cUguEA7fqJZh5K5qjIzV+WyNU4pnBvJcwhRo2txWGVgqVOhEuBLaZSpzfQ7exq/6tMueCNaNTHLHX+ZhYdar2ZEckxeaxn/F1woCPKLgchCwcEfj8="
      script: ./tools/check_sonarqube.sh
      cache:
        directories:
          - '$HOME/.sonar/cache'
      env: OPTS="sonarqube"
  fast_finish: true
